apiVersion: v1
summary: Respond to a Datadog alert via Jira
description: Automatically respond to a Datadog alert by creating an issue in Jira.
homepage: https://github.com/puppetlabs/relay-workflows/tree/master/datadog-to-jira
tags:
  - incident response

parameters:
  eventBody:
    description: Datadog event body
  eventTitle:
    description: Datadog event title
  eventType:
    description: Datadog event type
  jiraProjectKey:
    description: the JIRA project key to use when creating tickets
    default: OPS

triggers:
- name: datadog
  source:
    type: webhook
    image: relaysh/datadog-trigger-event-fired
  binding:
    parameters:
      eventBody: !Data body
      eventTitle: !Data title
      eventType: !Data event_type

steps:
- name: jira-issue-create
  image: relaysh/jira-step-issue-create
  when: !Fn.equals [!Parameter eventType, query_alert_monitor]
  spec:
    connection: !Connection { type: jira, name: my-jira-connection}
    issue:
      fields:
        description: !Fn.convertMarkdown [jira, !Parameter eventBody]
        project:
          key: !Parameter jiraProjectKey
        summary: !Parameter eventTitle
        type:
          name: Task
