apiVersion: v1
summary: Respond to a PagerDuty incident with Slack
description: >
  This workflow responds to a PagerDuty incident by sending a message to a Slack channel. The urgency of the incident determines which Slack channel the message goes to.
homepage: https://github.com/puppetlabs/relay-workflows/tree/master/pagerduty-to-slack
tags:
  - incident response

parameters:
  lowUrgencySlackChannel:
    description: the Slack channel to send low-urgency notifications to
    default: '#it'
  highUrgencySlackChannel:
    description: the Slack channel to send high-urgency notifications to
    default: '#on-call'
  incidentTitle:
    description: a brief summary of the incident
  incidentUrgency:
    description: the urgency of the incident
  incidentURL:
    description: a link to more information about the incident
  serviceName:
    description: the service that triggered the incident

locals:
  message: &message !Fn.concat
  - '⚠️ *<'
  - !Parameter incidentURL
  - '|'
  - !Parameter incidentTitle
  - '>* ⚠️'
  - "\nAffected service: "
  - !Parameter serviceName

triggers:
- name: pagerduty
  source:
    type: webhook
    image: relaysh/pagerduty-trigger-incident-triggered
  binding:
    parameters:
      incidentTitle: !Data title
      incidentUrgency: !Data urgency
      incidentURL: !Data appURL
      serviceName: !Data serviceName

steps:
- name: high-urgency-message
  image: relaysh/slack-step-message-send
  when: !Fn.notEquals [!Parameter incidentUrgency, low]
  spec:
    connection: !Connection {type: slack, name: my-slack-account}
    channel: !Parameter highUrgencySlackChannel
    username: PagerDuty via Relay
    message: *message
- name: low-urgency-message
  image: relaysh/slack-step-message-send
  when: !Fn.equals [!Parameter incidentUrgency, low]
  spec:
    connection: !Connection {type: slack, name: my-slack-account}
    channel: !Parameter lowUrgencySlackChannel
    username: PagerDuty via Relay
    message: *message
